# Generated by Django 3.2.6 on 2021-08-12 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studyvisapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timemodel',
            old_name='end',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='timemodel',
            old_name='start',
            new_name='endtime',
        ),
        migrations.AddField(
            model_name='timemodel',
            name='starttime',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
