# Generated by Django 3.2.6 on 2021-08-12 05:10

from datetime import timedelta
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("studyvisapp", "0002_auto_20210812_0433"),
    ]

    operations = [
        migrations.AddField(
            model_name="timemodel",
            name="duration",
            field=models.DurationField(default=timedelta()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="timemodel",
            name="endtime",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="timemodel",
            name="starttime",
            field=models.DateTimeField(),
        ),
    ]
