# Generated by Django 3.2.6 on 2021-08-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyvisapp', '0003_auto_20210812_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timemodel',
            name='date',
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='item',
            field=models.CharField(choices=[('danger', '機械学習'), ('warning', '統計')], max_length=50),
        ),
    ]
