# Generated by Django 3.2.6 on 2021-08-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyvisapp', '0005_alter_timemodel_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemodel',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
