# Generated by Django 3.2.6 on 2021-08-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyvisapp', '0006_auto_20210812_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemodel',
            name='endtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='starttime',
            field=models.DateTimeField(null=True),
        ),
    ]
